// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwXhytyntBnWw5HHc4LA9UqfCIwk3bZw8',
    appId: '1:416863663114:web:05f774d1dfd759bef6dbf3',
    messagingSenderId: '416863663114',
    projectId: 'mutemaidservice-5c04b',
    authDomain: 'mutemaidservice-5c04b.firebaseapp.com',
    storageBucket: 'mutemaidservice-5c04b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRCWJG-f5eQwGmPNXZJkW0GlJ7CttreNY',
    appId: '1:416863663114:android:becd313d907173bcf6dbf3',
    messagingSenderId: '416863663114',
    projectId: 'mutemaidservice-5c04b',
    storageBucket: 'mutemaidservice-5c04b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOLJL0mIevVyKGQc3_t4_xQdRf0QmnQN4',
    appId: '1:416863663114:ios:0a242103b8746f65f6dbf3',
    messagingSenderId: '416863663114',
    projectId: 'mutemaidservice-5c04b',
    storageBucket: 'mutemaidservice-5c04b.appspot.com',
    iosClientId: '416863663114-0kvh0dkpm4as64rk05vsccib5kei44pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mutemaidservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOLJL0mIevVyKGQc3_t4_xQdRf0QmnQN4',
    appId: '1:416863663114:ios:0a242103b8746f65f6dbf3',
    messagingSenderId: '416863663114',
    projectId: 'mutemaidservice-5c04b',
    storageBucket: 'mutemaidservice-5c04b.appspot.com',
    iosClientId: '416863663114-0kvh0dkpm4as64rk05vsccib5kei44pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mutemaidservice',
  );
}
